apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
spec:
  selector:
    matchLabels:
      app: neo4j
  replicas: 1
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      enableServiceLinks: false
      containers:
      - name: neo4j
        image: neo4j:5.15.0
        env:
        - name: NEO4J_AUTH
          value: "neo4j/password"
        ports:
        - containerPort: 7474
          name: http
        - containerPort: 7687
          name: bolt
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
spec:
  ports:
  - port: 7474
    targetPort: 7474
    name: http
  - port: 7687
    targetPort: 7687
    name: bolt
  selector:
    app: neo4j
